#!/bin/bash

# track all new files in a mercurial repository
# works from anywhere in the repository

main () {
    hg status $(hg root) | while read line; do
	state=${line:0:1}
	file_name=${line:2}
	
	[ $state == '?' ] && ( hg add $file_name )
    done
}

main "$@"
