#!/bin/bash

# java-getter-setter <type> <var1> [ var2, var3, ... ]
#
# Options:
#   -p -- define a prefix for the object-level variables. Defaults to "this."
#
# E.g.
# > java-getter-setter Boolean isTheRealLife isJustFantasy
# public Boolean getIsTheRealLife() {
#     return this.isTheRealLife;
# }
# 
# public void setIsTheRealLife(Boolean isTheRealLife) {
#     this.isTheRealLife = isTheRealLife;
# }
#
# public Boolean getIsJustFantasy() {
#     return this.isJustFantasy;
# }
# 
# public void setIsJustFantasy(Boolean isJustFantasy) {
#     this.isJustFantasy = isJustFantasy;
# }
#
# > java-getter-setter -p "hello_" int world
# public int getWorld() {
#     return hello_world;
# }
# 
# public void setWorld(int world) {
#     hello_world = world;
# }



main () {
    local prefix="this.";

    while getopts ":p:" opt; do
	case $opt in
	    p)
		prefix=$OPTARG >&2
		;;
	esac
    done

    shift $((OPTIND - 1))

    for var in ${@:$(($1+2))}; do
        echo "public $1 get${var^}() {";
	echo "    return $prefix$var;";
	echo "}";
	echo
	echo "public void set${var^}($1 $var) {";
	echo "    $prefix$var = $var;";
	echo "}";
	echo
    done
}

if hash xclip 2>/dev/null; then
    main "$@" | xclip -selection c
else
    main "$@"
fi
